{{- if or .Values.kuma.enabled .Values.telegram.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cert-sentinel.fullname" . }}
  labels:
    {{- include "cert-sentinel.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.kuma.enabled }}
  kumaPushUrl: {{ .Values.kuma.pushUrl | quote }}
  {{- end }}
  {{- if .Values.telegram.enabled }}
  telegramBotToken: {{ .Values.telegram.botToken | quote }}
  telegramChatId: {{ .Values.telegram.chatId | quote }}
  {{- end }}
{{- end }}
