apiVersion: v1
kind: Service
metadata:
  name: hub-alloy
  namespace: monitoring
  labels:
    app.kubernetes.io/name: hub-alloy
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: hub-alloy
  ports:
    - name: http-metrics
      port: 12345
      targetPort: 12345
      protocol: TCP
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: 4318
      protocol: TCP
    - name: prom-receive
      port: 19090
      targetPort: 19090
      protocol: TCP
